/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        // Full Material You token set from DESIGN.md (Scholar's Terminal)
        "surface-container-highest": "#38342d",
        "surface-container-low":     "#1e1b15",
        "primary-fixed":             "#ffe08f",
        "on-error-container":        "#ffdad6",
        "inverse-primary":           "#755b00",
        "surface-tint":              "#e6c364",
        "on-secondary-fixed":        "#1d1c17",
        "outline":                   "#99907e",
        "secondary-fixed-dim":       "#cac6be",
        "error":                     "#ffb4ab",
        "secondary-fixed":           "#e7e2da",
        "inverse-surface":           "#e9e1d7",
        "on-tertiary":               "#1e2b66",
        "on-surface":                "#e9e1d7",
        "tertiary-container":        "#9ba8eb",
        "on-tertiary-fixed-variant": "#35437e",
        "surface-bright":            "#3d3931",
        "primary":                   "#e6c364",
        "outline-variant":           "#4d4637",
        "secondary":                 "#cac6be",
        "background":                "#16130d",
        "on-primary":                "#3d2e00",
        "on-tertiary-fixed":         "#041451",
        "on-background":             "#e9e1d7",
        "surface-container":         "#221f19",
        "inverse-on-surface":        "#343029",
        "on-primary-fixed-variant":  "#584400",
        "on-surface-variant":        "#d0c5b2",
        "on-error":                  "#690005",
        "error-container":           "#93000a",
        "on-secondary":              "#32302b",
        "surface":                   "#16130d",
        "surface-container-lowest":  "#100e08",
        "tertiary-fixed-dim":        "#b9c3ff",
        "primary-fixed-dim":         "#e6c364",
        "on-secondary-fixed-variant":"#494741",
        "surface-container-high":    "#2d2a23",
        "on-secondary-container":    "#b9b5ad",
        "surface-dim":               "#16130d",
        "on-primary-container":      "#503d00",
        "on-tertiary-container":     "#2e3b77",
        "tertiary":                  "#b9c4ff",
        "tertiary-fixed":            "#dde1ff",
        "secondary-container":       "#494741",
        "primary-container":         "#c9a84c",
        "on-primary-fixed":          "#241a00",
        "surface-variant":           "#38342d",
        // Custom semantic tokens
        "gate-warning":              "#D4742A",
        "success":                   "#4A9E6F",
      },
      fontFamily: {
        playfair:   ["'Playfair Display'", "serif"],
        sans:       ["'DM Sans'", "sans-serif"],
        mono:       ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "display":     ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "heading":     ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        "mono-ui":     ["13px", { lineHeight: "1.4", letterSpacing: "0.02em",  fontWeight: "500" }],
        "body-lg":     ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md":     ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm":     ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "mono-label":  ["11px", { lineHeight: "1",   letterSpacing: "0.05em", fontWeight: "500" }],
      },
      borderRadius: {
        sm:      "0.125rem",
        DEFAULT: "0.25rem",
        md:      "0.375rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        full:    "9999px",
      },
      spacing: {
        gutter: "20px",
        margin: "32px",
        xs:     "4px",
        sm:     "8px",
        md:     "16px",
        lg:     "24px",
        xl:     "40px",
      },
      keyframes: {
        fadeUp: {
          "0%":   { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideIn: {
          "0%":   { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        gateFlash: {
          "0%, 100%": { borderLeftColor: "#D4742A" },
          "50%":      { borderLeftColor: "rgba(212,116,42,0.3)" },
        },
        cursorBlink: {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0" },
        },
      },
      animation: {
        "fade-up":    "fadeUp 0.4s ease-out both",
        "slide-in":   "slideIn 0.3s ease-out both",
        "gate-flash": "gateFlash 0.6s ease-in-out 2",
        "cursor":     "cursorBlink 0.8s step-end infinite",
      },
    },
  },
  plugins: [],
};
